# Generated by Django 5.0 on 2026-07-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborder',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='laborder',
            name='verification_hash',
            field=models.CharField(blank=True, help_text='Encoded into report QR code for tamper-proof verification', max_length=32, unique=True),
        ),
        migrations.AddField(
            model_name='laborder',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labresult',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('analyzer', 'Analyzer Machine')], default='manual', max_length=20),
        ),
    ]
