# Generated by Django 5.0 on 2026-06-27 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clinic_logos/')),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField()),
                ('is_lab_enabled', models.BooleanField(default=True)),
                ('is_pharmacy_enabled', models.BooleanField(default=True)),
                ('is_hr_enabled', models.BooleanField(default=True)),
                ('is_reception_enabled', models.BooleanField(default=True)),
                ('is_doctor_enabled', models.BooleanField(default=True)),
                ('is_billing_enabled', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_suspended', models.BooleanField(default=False)),
                ('suspension_reason', models.TextField(blank=True)),
                ('plan', models.CharField(choices=[('basic', 'Basic'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='professional', max_length=50)),
                ('plan_expires', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Clinic',
                'verbose_name_plural': 'Clinics',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clinic')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('clinic_admin', 'Clinic Admin'), ('doctor', 'Doctor'), ('lab_supervisor', 'Lab Supervisor'), ('pharmacist', 'Pharmacist'), ('receptionist', 'Receptionist'), ('hr_manager', 'HR Manager'), ('accountant', 'Accountant')], max_length=30)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('cnic', models.CharField(blank=True, max_length=15, verbose_name='CNIC')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='staff_avatars/')),
                ('is_active', models.BooleanField(default=True)),
                ('can_delete_lab_results', models.BooleanField(default=False)),
                ('joined_at', models.DateField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='core.clinic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Profile',
            },
        ),
    ]
