# Generated by Django 5.0 on 2026-07-02 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('doctor', '0002_initial'),
        ('laboratory', '0002_laborder_is_verified_laborder_verification_hash_and_more'),
        ('reception', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='dispatched_to_lab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dispatched_to_pharmacy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescription',
            name='icd11_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='ICD-11 Code'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='lab_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_prescription', to='laboratory.laborder'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='reception.token'),
        ),
        migrations.CreateModel(
            name='TreatmentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. Typhoid Plan, Cold & Flu, Hypertension', max_length=120)),
                ('icon', models.CharField(default='⭐', help_text='Emoji shown on the quick-button', max_length=10)),
                ('icd11_code', models.CharField(blank=True, max_length=20, verbose_name='ICD-11 Code')),
                ('diagnosis_text', models.CharField(blank=True, max_length=255)),
                ('chief_complaint_text', models.CharField(blank=True, max_length=255)),
                ('medicines_json', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.clinic')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('lab_tests', models.ManyToManyField(blank=True, related_name='templates', to='laboratory.labtestcatalog')),
            ],
            options={
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.AddField(
            model_name='prescription',
            name='template_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.treatmenttemplate'),
        ),
    ]
